# Generated by Django 3.2.7 on 2021-10-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0002_auto_20211002_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprev',
            name='shoprevImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
