# Generated by Django 3.2.7 on 2021-10-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0003_alter_shoprev_shoprevimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='themeID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='ResID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevNRecom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevRecom',
            field=models.IntegerField(default=0),
        ),
    ]
