# Generated by Django 2.2 on 2021-10-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0005_auto_20211007_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprev',
            name='shoprevImage',
            field=models.ImageField(blank=True, upload_to='shopImages'),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevImage',
            field=models.ImageField(blank=True, upload_to='themeImages'),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='theme_ID',
            field=models.ForeignKey(db_column='themeID', on_delete=django.db.models.deletion.CASCADE, related_name='theme_ID', to='BANGAPP.Theme'),
        ),
    ]
