# Generated by Django 2.2 on 2021-10-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0009_auto_20211007_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hate_record', to='BANGAPP.ThemeRev')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hate_record', to='BANGAPP.User')),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
    ]
