# Generated by Django 2.2 on 2021-11-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0010_hate'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='themeIntro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='themeRevImage',
            field=models.ImageField(blank=True, upload_to='themeImages'),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevImage',
            field=models.ImageField(blank=True, upload_to='themeRevImages'),
        ),
    ]
