# Generated by Django 2.2 on 2021-11-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0011_auto_20211110_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='themeRevImage',
        ),
        migrations.AddField(
            model_name='theme',
            name='themeImage',
            field=models.ImageField(blank=True, upload_to='themeImagesT'),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevImage',
            field=models.ImageField(blank=True, upload_to='themeImages'),
        ),
    ]
