# Generated by Django 2.2 on 2021-11-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0015_auto_20211112_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='score',
            new_name='themeRating',
        ),
    ]
