# Generated by Django 2.2 on 2021-11-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0018_shop_shopimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themerev',
            name='ResID',
        ),
        migrations.RemoveField(
            model_name='themerev',
            name='themeRevActivity',
        ),
        migrations.RemoveField(
            model_name='themerev',
            name='themeRevDifficulty',
        ),
        migrations.RemoveField(
            model_name='themerev',
            name='themeRevHorror',
        ),
        migrations.RemoveField(
            model_name='themerev',
            name='themeRevImage',
        ),
        migrations.RemoveField(
            model_name='themerev',
            name='themeRevOccurredTime',
        ),
        migrations.RemoveField(
            model_name='themerev',
            name='themeRevRating',
        ),
        migrations.RemoveField(
            model_name='themerev',
            name='themeRevResult',
        ),
    ]
