# Generated by Django 2.2 on 2021-11-19 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0021_auto_20211119_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='ShopID',
            field=models.ForeignKey(db_column='ShopID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ShopId', to='BANGAPP.Shop'),
        ),
    ]
