# Generated by Django 2.2 on 2021-12-08 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0027_remove_themerev_themerevtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='con',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='nrc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='rc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='wr',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevRating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
