# Generated by Django 2.2 on 2021-12-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0028_auto_20211209_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='wr',
        ),
    ]
