# Generated by Django 2.2 on 2021-12-11 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0036_auto_20211212_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 0, 19, 59, 431807)),
        ),
        migrations.AlterField(
            model_name='test',
            name='themeRevNRecom',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='themeRevRecom',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
