# Generated by Django 2.2 on 2021-12-11 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0042_auto_20211212_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 1, 41, 4, 651904)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevWriteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 1, 41, 4, 651141)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='theme_ID',
            field=models.ForeignKey(db_column='theme_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theme_ID', to='BANGAPP.Theme'),
        ),
    ]
