# Generated by Django 2.2 on 2021-12-14 01:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0048_auto_20211213_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='themeRevRecom',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 14, 1, 21, 55, 330591)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevWriteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 14, 1, 21, 55, 329679)),
        ),
        migrations.CreateModel(
            name='ThemeLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liketheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themelike_record', to='BANGAPP.Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themelike_record', to='BANGAPP.User')),
            ],
            options={
                'unique_together': {('user', 'liketheme')},
            },
        ),
    ]
