# Generated by Django 2.2 on 2021-12-14 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0049_auto_20211214_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='themeRevRecom',
            new_name='themeLike',
        ),
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 14, 1, 23, 36, 802596)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevWriteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 14, 1, 23, 36, 801685)),
        ),
    ]
