# Generated by Django 2.2 on 2021-12-15 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0050_auto_20211214_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 15, 0, 1, 34, 821487)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevWriteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 15, 0, 1, 34, 820593)),
        ),
    ]
