# Generated by Django 2.2 on 2021-12-15 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0051_auto_20211215_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 15, 16, 50, 0, 477766)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevWriteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 15, 16, 50, 0, 476872)),
        ),
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(blank=True, default='userImages/plus.png', upload_to='userImages/'),
        ),
    ]
