# Generated by Django 4.0 on 2021-12-21 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0054_theme_themeprice_alter_hate_id_alter_like_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 21, 22, 15, 23, 7809)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevWriteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 21, 22, 15, 23, 6796)),
        ),
    ]
