# Generated by Django 3.2.7 on 2021-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='Difficulty',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='Horror',
        ),
        migrations.AlterField(
            model_name='theme',
            name='themeID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
