# Generated by Django 2.2 on 2021-11-11 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0013_auto_20211111_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='themeImage',
            field=models.ImageField(blank=True, upload_to='themeImages/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='themeRating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
