# Generated by Django 2.2 on 2021-11-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0019_auto_20211119_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='themerev',
            name='shop_ID',
            field=models.ForeignKey(db_column='shop_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_ID', to='BANGAPP.Shop'),
        ),
    ]
