# Generated by Django 2.2 on 2021-11-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0020_themerev_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='themeRating',
            field=models.IntegerField(default=0),
        ),
    ]
