# Generated by Django 2.2 on 2021-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0022_auto_20211120_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='themerev',
            name='themeRating',
            field=models.IntegerField(default=0),
        ),
    ]
