# Generated by Django 2.2 on 2021-12-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0023_themerev_themerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themerev',
            old_name='themeRating',
            new_name='themeRevRating',
        ),
    ]
