# Generated by Django 2.2 on 2021-12-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0029_remove_test_wr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='nrc',
        ),
        migrations.RemoveField(
            model_name='test',
            name='rc',
        ),
    ]
