# Generated by Django 2.2 on 2021-12-10 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0032_test_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
