# Generated by Django 2.2 on 2021-12-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0033_auto_20211211_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='con',
        ),
    ]
