# Generated by Django 2.2 on 2021-12-11 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0035_test_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 0, 13, 49, 928143)),
        ),
        migrations.AddField(
            model_name='test',
            name='themeRevNRecom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='themeRevRecom',
            field=models.IntegerField(default=0),
        ),
    ]
