# Generated by Django 2.2 on 2021-12-11 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0037_auto_20211212_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='shop_ID2',
            field=models.ForeignKey(db_column='test2', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test2', to='BANGAPP.Shop'),
        ),
        migrations.AddField(
            model_name='test',
            name='theme_ID2',
            field=models.ForeignKey(db_column='test1', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test1', to='BANGAPP.Theme'),
        ),
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 0, 35, 13, 632993)),
        ),
    ]
