# Generated by Django 2.2 on 2021-12-11 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0040_auto_20211212_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 0, 49, 14, 594235)),
        ),
        migrations.AlterField(
            model_name='test',
            name='WriterID2',
            field=models.ForeignKey(blank=True, db_column='test3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test3', to='BANGAPP.User'),
        ),
    ]
