# Generated by Django 2.2 on 2021-12-11 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0043_auto_20211212_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 4, 53, 20, 826380)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='shop_ID',
            field=models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, related_name='shop_ID', to='BANGAPP.Shop'),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevWriteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 4, 53, 20, 825629)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='theme_ID',
            field=models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.CASCADE, related_name='theme_ID', to='BANGAPP.Theme'),
        ),
    ]
