# Generated by Django 2.2 on 2021-12-12 04:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0044_auto_20211212_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 13, 43, 4, 937095)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevWriteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 13, 43, 4, 936331)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRev_WriterID',
            field=models.ForeignKey(blank=True, db_column='themeRev_WriterID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='themeRev_WriterID', to='BANGAPP.User'),
        ),
    ]
