# Generated by Django 2.2 on 2021-12-13 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANGAPP', '0047_auto_20211213_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='WDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 13, 3, 25, 35, 809418)),
        ),
        migrations.AlterField(
            model_name='themerev',
            name='themeRevWriteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 13, 3, 25, 35, 808637)),
        ),
    ]
